### PR TITLE
Fix eclipse/xtext#1907

### LINKED ISSUE #1907: Change API-DIFF Job to use default image
Change API-DIFF Job to use default image instead of our custom

### PR DESCRIPTION
**Pull request by cdietrich**
Fix eclipse/xtext#1907

### CODE REVIEW

**Comment by cdietrich** [comment]
unfortunately the compare is still empty. the question is why
maybe the wrong thing is compared with the script rework by karsten

File: create-api-diff.sh [hunk 1]
```diff
@@ -1,121 +1,110 @@
...
 
-if [ ! -d tmf-xtext-Update-2.23.0 ];
-then
-   echo "Downloading Xtext 2.23.0"
-   curl -m 1200 -sL 'download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.23.0/R202008310926/tmf-xtext-Update-2.23.0.zip' --output 'tmf-xtext-Update-2.23.0.zip' && unzip -q tmf-xtext-Update-2.23.0.zip -d tmf-xtext-Update-2.23.0
-   rm tmf-xtext-Update-2.23.0.zip
-fi
+   # only download relevant versions
+   if [ $VERSION == $NEW_VERSION ] || [ $VERSION == $OLD_VERSION ]; then
+      download $VERSION "https://download.eclipse.org/modeling/tmf/xtext/downloads/drops/$VERSION/$BUILD_ID/tmf-xtext-Update-$VERSION.zip"
```
Comment (cdietrich) [inline create-api-diff.sh:100]: fix for the wrong version downloaded problem. what do you think @kthoms

**Review by kthoms — APPROVED** [review]
Need to clarify why the result is empty, but this out of scope of the build change.

File: create-api-diff.sh (hunk 1 above)
Comment (kthoms) [reply create-api-diff.sh:100]: Looks fine to me

**Comment by cdietrich** [comment]
empty problem solved by picking correct download url

**Comment by kthoms** [comment]
Now the report looks fine https://ci.eclipse.org/xtext/job/releng/job/xtext-xtend-api-diff/714/artifact/output/

**Comment by cdietrich** [comment]
@NicoPrediger would be nice if you could have another look at the bash script / Jenkins file changes

File: Jenkinsfile [hunk 2]
```diff
@@ -1,8 +1,8 @@
 pipeline {
   agent {
     kubernetes {
-      label 'xtext-xtend-api-diff-' + env.BUILD_NUMBER
-      defaultContainer 'xtext-buildenv'
+      label 'xtext-xtend-api-diff'
```
Comment (NicoPrediger) [inline Jenkinsfile]: Why don't we remove the custom pod completely? I don't see anything special in this podtemplate, maybe we shouln't maintain it at all then. (See https://github.com/eclipse/xtext-core/blob/master/Jenkinsfile for example)

File: Jenkinsfile [hunk 3]
```diff
@@ -134,12 +103,14 @@ spec:
               color = '#666666'
           }
 
+          /*
```
Comment (NicoPrediger) [inline Jenkinsfile]: Is this intentionally still commented out?

File: create-api-diff.sh [hunk 4]
```diff
@@ -1,121 +1,110 @@
...
-if [ -d tmf-xtext-Update-2.26.0 ];
-then
-  rm -r tmf-xtext-Update-2.26.0
-fi
-echo "Downloading Xtext 2.26.0"
-# TODO make this better and faster. am not sure if we can guess the nightly number. or ....
-# ideally download official nightly
-curl -m 1200 --retry 5 -sL 'https://ci.eclipse.org/xtext/job/xtext-umbrella/job/master/lastStableBuild/artifact/build/org.eclipse.xtext.sdk.p2-repository-2.26.0-SNAPSHOT.zip' --output 'tmf-xtext-Update-2.26.0.zip' && unzip -q tmf-xtext-Update-2.26.0.zip -d tmf-xtext-Update-2.26.0
-rm tmf-xtext-Update-2.26.0.zip
+echo ""
```
Comment (NicoPrediger) [inline create-api-diff.sh:106]: Why?

File: Jenkinsfile (hunk 2 above)
Comment (cdietrich) [reply Jenkinsfile]: without it seems slow like crap

File: create-api-diff.sh (hunk 4 above)
Comment (cdietrich) [reply create-api-diff.sh:106]: empty line?

**Comment by cdietrich** [comment]
@NicoPrediger please re-review

File: Jenkinsfile (hunk 2 above)
Comment (NicoPrediger) [reply Jenkinsfile]: The do offer additional labels for more resources, in xtext-xtend we use:
> label 'centos-7-6gb'

I did a quick search, but couldn't find a list of available labels, but it might be worth it to try this one...

Comment (cdietrich) [reply Jenkinsfile]: its working anyway so i think we are fine. maybe just a slow machine in pool problem

**Review by NicoPrediger — APPROVED** [review]
